# Empty listen_addresses to use systemd socket activation
listen_addresses = ['127.0.0.16:53']
#user_name='_dnscrypt-proxy'

#server_names = ['cloudflare']
ipv4_servers = true
dnscrypt_servers = true
doh_servers = false
require_dnssec = true
require_nolog = true
require_nofilter = true

timeout = 5000

cert_refresh_delay = 240
dnscrypt_ephemeral_keys = false

fallback_resolver = '9.9.9.9:53'
ignore_system_dns = true

cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = './public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
